#!/usr/bin/env python3
"""Emit case-alias forwarding headers for MSVC-style #include spellings.

Windows header lookup is case-insensitive; the Linux build host's is
not.  Third-party CE sources written against MSVC legitimately spell
platform includes as <Windows.h> or <Shellapi.h>.  For every #include
spelling used by an application tree whose exact-case file is absent
from the sysroot but whose case-insensitive match exists, this writes
<out>/<Spelling> forwarding to the real header.

Aliases can never shadow a real sysroot header: only spellings with no
exact-case file are emitted.  Run this at application-build time (see
build-easyrpg-player.sh) in addition to the static overlay aliases
(Windows.h, Shellapi.h) so that any future mismatched spelling surfaces
as a generated file rather than as a build failure.

Usage:
    gen-include-aliases.py --sysroot-include DIR --source DIR --out DIR
"""

import argparse
import os
import re
import sys

INCLUDE_RE = re.compile(r'^\s*#\s*include\s*[<"]([^<">]+)[>"]')
SRC_EXT = ('.c', '.cc', '.cpp', '.cxx', '.h', '.hh', '.hpp', '.inl')
HDR_EXT = ('.h', '.hh', '.hpp', '.inl')


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--sysroot-include', required=True,
                    help='the sysroot include directory to match against')
    ap.add_argument('--source', required=True,
                    help='application tree to scan recursively')
    ap.add_argument('--out', required=True,
                    help='directory to write alias headers into')
    args = ap.parse_args()

    # index: lowercase basename -> set of actual spellings in the sysroot
    index = {}
    for dp, _dn, fn in os.walk(args.sysroot_include):
        for f in fn:
            if f.endswith(HDR_EXT):
                index.setdefault(f.lower(), set()).add(f)

    missing = set()
    for dp, _dn, fn in os.walk(args.source):
        for f in fn:
            if not f.endswith(SRC_EXT):
                continue
            path = os.path.join(dp, f)
            try:
                lines = open(path, encoding='utf-8', errors='replace')
            except OSError:
                continue
            with lines:
                for line in lines:
                    m = INCLUDE_RE.match(line)
                    if not m:
                        continue
                    name = m.group(1)
                    if '/' in name:
                        continue  # project-relative includes are not ours
                    spellings = index.get(name.lower())
                    if not spellings or name in spellings:
                        continue  # absent from sysroot, or already exact-case
                    missing.add(name)

    os.makedirs(args.out, exist_ok=True)
    for name in sorted(missing):
        spellings = sorted(index[name.lower()])
        # the sysroot must not contain two headers differing only by case;
        # if it ever does, refuse to guess rather than shadow arbitrarily
        if len(spellings) != 1:
            print('%s: ambiguous sysroot match for %s: %s'
                  % (os.path.basename(sys.argv[0]), name, spellings),
                  file=sys.stderr)
            return 1
        real = spellings[0]
        with open(os.path.join(args.out, name), 'w') as fh:
            fh.write('#pragma once\n')
            fh.write('/* Case-alias forwarding header (MSVC-style spelling);\n'
                     '   the real header is %s.  Generated by\n'
                     '   sysroot/gen-include-aliases.py - do not edit. */\n'
                     % real)
            fh.write('#include "%s"\n' % real)
        print('alias: %s -> %s' % (name, real))
    return 0


if __name__ == '__main__':
    sys.exit(main())
